export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const FAVORITES_LOADING = 'FAVORITES_LOADING';
export const FAVORITES_FAILED = 'FAVORITES_FAILED';
export const ADD_FAVORITES = 'ADD_FAVORITES';

export const COINS_LOADING = 'COINS_LOADING';
export const COINS_FAILED = 'COINS_FAILED';
export const ADD_COINS = 'ADD_COINS';

export const VOLATILITY_LOADING = 'VOLATILITY_LOADING';
export const VOLATILITY_FAILED = 'VOLATILITY_FAILED';
export const ADD_VOLATILITY = 'ADD_VOLATILITY';